receivers:
  otlp:
    protocols:
      grpc:
      #http:

processors:
  batch:

exporters:
  # OTLP
  otlp:
    endpoint: otelcol:4317
  # Data sources: traces
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  # Data sources: traces, metrics, logs
  logging:
    loglevel: debug
  # Data sources: traces
  jaeger:
    endpoint: "jaeger-all-in-one:14250"
    tls:
      insecure: true
  # Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]